name: sheet
description: A fully customizable draggable bottom sheet.
version: 1.0.0
homepage: https://github.com/jamesblasco/modal_bottom_sheet

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
   
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  lints: ^2.0.0

flutter: